name: Memory Management Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install valgrind
      run: sudo apt-get update && sudo apt-get install -y valgrind

    - name: make wa
      run: make test_wa_matrix
    - name: valgrind wa
      run: valgrind --error-exitcode=1 -s --leak-check=full ./out

    - name: make ngl
      run: make test_ngl_matrix
    - name: valgrind ngl
      run: valgrind --error-exitcode=1 -s --leak-check=full ./out

    - name: make
      run: make
    - name: valgrind spkmeans
      run: valgrind --error-exitcode=1 -s --leak-check=full ./spkmeans lnorm tests/blobs1.txt

    - name: clean
      run: make clean
